
 services:
  househunt:
    build: .
    user: "${UID}:${GID}"
    env_file:
      - .env
    environment:
      # Any other environment variables can be specified here if needed.
      - DB_FILENAME=/data/househunt.db
      - HTTP_VIEW_DIR=/assets/templates
    volumes:
      - ./.localdev:/data
      - ./assets:/assets
    ports:
      - "8888:8888"
